version: "3"
services:
    api:
        build: .
        depends_on:
            - postgres
        ports: 
            - 8000:8000
        volumes:
          - ./:/usr/src/app:ro
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload # reload for every change docker is refresh
        # env_file:
        # - ./.env
        environment:
          - DATABASE_HOSTNAME=postgres
          - DATABASE_PORT=5432
          - DATABASE_PASSWORD=admin
          - DATABASE_NAME=fastapi
          - DATABASE_USERNAME=postgres
          - SECRET_KEY=9009304235D09SFSFY9SHDF9ASDF7D0809DSF6623423H4OH35435HOI2H345H6-5T09DFGS09DFG
          - ALGORITHM=HS256
          - ACCESS_TOKEN_EXPIRE_MINUTES=30 
    postgres: 
      image: postgres
      environment:
          - POSTGRES_PASSWORD=admin
          - POSTGRES_DB=fastapi

      volumes:
        - postgres-db:/var/lib/postgresql/data
volumes:
    postgres-db: